### ISSUE TITLE
Where should I do the net request?

### ISSUE THREAD

**Issue by fengbaobao** [dmilicic/Android-Clean-Boilerplate#5]
Hi dmilicic:
    I read an article about your Clean Architecture(They call so). I have read "Android-Clean-Boilerplate" and "android-clean-sample-app" source wrote by you. 

```
I wonder where should I do the net request?

I know I can get data from database via the "Interactor". But the third part net request library such as AsyncHttpTask has already do work at a new thread. So if I put MVP in the outer layer, may I put the net request at M of the MVP?

 Answer from a AndroidRookies. THKS a lot if get your help~
```

**Comment by dmilicic** [comment]
Hey!

You can check out how to do network requests [here](https://github.com/dmilicic/android-clean-sample-app/tree/master/app/src/main/java/com/kodelabs/mycosts/network). This part of the code implements all [Retrofit ](https://square.github.io/retrofit/) needs to make network requests. Retrofit is a 3rd party library for network requests.

You can see how the actual network requests are called [here](https://github.com/dmilicic/android-clean-sample-app/blob/master/app/src/main/java/com/kodelabs/mycosts/sync/SyncAdapter.java). Take a look from line 115. where the actual request happens. The `SyncAdapter` always runs in a background thread so I am allowed to make a blocking request.

You are correct. Since MVP is the outer layer, you can put net request code there without breaking clean principles! However, I usually don't have networking code in my MVP models. They serve only as ViewModels. This means they are dumb classes only responsible for displaying data to the UI. But you are allowed to do whatever you think works best for your project.

I hope this helps!
