### ISSUE TITLE
One new Interactor for every new Operation?

### ISSUE THREAD

**Issue by felipecaldas** [dmilicic/Android-Clean-Boilerplate#8]
Hi there,

I have just implemented the architecture as a candidate for my app.

I noticed that the InteractorImpl has a run() method. This is the only method that gets called from the Presenter/Activity if I understand correctly.

So, if I have a CRUD operation for my model, I would have to create GET, POST, DELETE, UPDATE interactor (that is, 4 different interactors) for the same Model....

Is this correct assumption? Is there any way I could avoid this? I would like to have one interactor that supports my presenter and that presenter supports a Activity.

Thanks

**Comment by dmilicic** [comment]
Hi,

There are several ways you could address this since you can modify the code in any way you wish. 

I prefer creating a separate Interactor for each (CRUD) operation since I believe it is a more SOLID approach. 

Another way you could do this is with the Command pattern. You can send a Command along with other data to the Interactor. And then you will have a switch case for each command depending on what you want to do (e.g. Command.GET, Command.POST, etc.). 

However, do note that you should rarely have a single Interactor responsible for your Presenter and Activity when building a slightly larger app. Otherwise, it might compromise how SOLID is your code.

Cheers!
